codecov:
  require_ci_to_pass: false
comment:
  behavior: default
  layout: "reach, diff, flags, files"


ignore:
  - "**/test_*"
  - "**/*_test.*"
  - "**/mocks/*"
  - "**/mock/*"

coverage:
  precision: 2
  range:
  - 50.0
  - 100.0
  round: down
  status:
    project: no
    patch: yes
    changes: yes
github_checks:
  annotations: true