// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	big "math/big"

	ethclient "github.com/ethereum/go-ethereum/ethclient"

	ethtypes "github.com/icon-project/icon-bridge/cmd/iconbridge/chain/common/eth/types"

	log "github.com/icon-project/icon-bridge/common/log"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// IClient is an autogenerated mock type for the IClient type
type IClient struct {
	mock.Mock
}

// GetBalance provides a mock function with given fields: ctx, hexAddr
func (_m *IClient) GetBalance(ctx context.Context, hexAddr string) (*big.Int, error) {
	ret := _m.Called(ctx, hexAddr)

	var r0 *big.Int
	if rf, ok := ret.Get(0).(func(context.Context, string) *big.Int); ok {
		r0 = rf(ctx, hexAddr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hexAddr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockNumber provides a mock function with given fields:
func (_m *IClient) GetBlockNumber() (uint64, error) {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockReceiptsFromHeight provides a mock function with given fields: height
func (_m *IClient) GetBlockReceiptsFromHeight(height *big.Int) (types.Receipts, error) {
	ret := _m.Called(height)

	var r0 types.Receipts
	if rf, ok := ret.Get(0).(func(*big.Int) types.Receipts); ok {
		r0 = rf(height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Receipts)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*big.Int) error); ok {
		r1 = rf(height)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChainID provides a mock function with given fields:
func (_m *IClient) GetChainID() *big.Int {
	ret := _m.Called()

	var r0 *big.Int
	if rf, ok := ret.Get(0).(func() *big.Int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	return r0
}

// GetEthClient provides a mock function with given fields:
func (_m *IClient) GetEthClient() *ethclient.Client {
	ret := _m.Called()

	var r0 *ethclient.Client
	if rf, ok := ret.Get(0).(func() *ethclient.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethclient.Client)
		}
	}

	return r0
}

// GetHeaderByHeight provides a mock function with given fields: height
func (_m *IClient) GetHeaderByHeight(height *big.Int) (*ethtypes.Header, error) {
	ret := _m.Called(height)

	var r0 *ethtypes.Header
	if rf, ok := ret.Get(0).(func(*big.Int) *ethtypes.Header); ok {
		r0 = rf(height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethtypes.Header)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*big.Int) error); ok {
		r1 = rf(height)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Log provides a mock function with given fields:
func (_m *IClient) Log() log.Logger {
	ret := _m.Called()

	var r0 log.Logger
	if rf, ok := ret.Get(0).(func() log.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Logger)
		}
	}

	return r0
}

type mockConstructorTestingTNewIClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewIClient creates a new instance of IClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIClient(t mockConstructorTestingTNewIClient) *IClient {
	mock := &IClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
