buildsc:
	./build.sh buildsc

buildnodes:
	./build.sh buildnodes

runnodes:
	./build.sh runnodes

deploysclocalnet:
	./build.sh deploysclocalnet
	
# Usage: make deploysc net=mainnet/testnet
deploysc:
	./build.sh deploysc ${net}

# Usage: make deployscarctic net=mainnet/testnet
deployscarctic:
	./build.sh deployscarctic ${net}

############## AUDIT FIXES ############## 

# Usage: make auditfixbsc net=mainnet
auditfixbsc:
	./build.sh bscaudit ${net}

auditfixarctic:
	./build.sh arcticaudit ${net}

auditfixicon:
	./build.sh iconaudit ${net}

#########################################

runrelaysrc:
	./build.sh runrelaysrc

stopnodes:
	./build.sh stopnodes

cleanartifacts:
	./build.sh cleanartifacts

buildrelayimg:
	./build.sh buildrelayimg

runrelayimg:
	./build.sh runrelayimg

rune2etests:
	./build.sh rune2etests

stoprelayimg:
	./build.sh stoprelayimg	

buildimglocal:
	./build.sh buildimg

runimglocal:
	./build.sh runimglocal

cleanimglocal:
	./build.sh cleanimglocal

removeimglocal:
	./build.sh runimglocal