ARG BASE_IMAGE
FROM ${BASE_IMAGE}
LABEL MAINTAINER="t_arch@iconloop.com"
# install dependencies
#RUN apk add --no-cache jq

ARG VERSION
LABEL ICONBRIDGE_VERSION="$VERSION"

RUN apk add build-base

RUN apk add inotify-tools

# install
COPY dist/bin/iconbridge /iconbridge/bin/iconbridge
ENV PATH $PATH:/iconbridge/bin

# copy extras
COPY dist/contracts/solidity /iconbridge/contracts/solidity
COPY dist/contracts/javascore /iconbridge/contracts/javascore
# copy module
COPY dist/debug/* /iconbridge/

WORKDIR /iconbridge

# container configuration
VOLUME ["/iconbridge/data"]

# goloop entrypoint
ENV ICONBRIDGE_BASE_DIR=/iconbridge/data
ENV ICONBRIDGE_CONFIG=/iconbridge/config/config.json
ENV ICONBRIDGE_KEY_STORE=/iconbridge/config/keystore.json
ENV ICONBRIDGE_KEY_SECRET=/iconbridge/config/keysecret
ENV ICONBRIDGE_LOG_WRITER_FILENAME=/iconbridge/data/iconbridge.log

RUN go mod download

RUN go get github.com/go-delve/delve/cmd/dlv

# entrypoint
RUN { \
        echo '#!/bin/sh'; \
        echo 'set -e'; \
        echo 'if [ "$ICONBRIDGE_CONFIG" != "" ] && [ ! -f "$ICONBRIDGE_CONFIG" ]; then'; \
        echo '  UNSET="ICONBRIDGE_CONFIG"' ; \
        echo '  CMD="ICONBRIDGE save $ICONBRIDGE_CONFIG"'; \
        echo '  if [ "$ICONBRIDGE_KEY_SECRET" != "" ] && [ ! -f "$ICONBRIDGE_KEY_SECRET" ]; then'; \
        echo '    mkdir -p $(dirname $ICONBRIDGE_KEY_SECRET)'; \
        echo '    echo -n $(date|md5sum|head -c16) > $ICONBRIDGE_KEY_SECRET' ; \
        echo '  fi'; \
        echo '  if [ "$ICONBRIDGE_KEY_STORE" != "" ] && [ ! -f "$ICONBRIDGE_KEY_STORE" ]; then'; \
        echo '    UNSET="$UNSET ICONBRIDGE_KEY_STORE"' ; \
        echo '    CMD="$CMD --save_key_store=$ICONBRIDGE_KEY_STORE"' ; \
        echo '  fi'; \
        echo '  if [ "$ICONBRIDGE_SRC_ADDRESS" != "" ] && [ -f "$ICONBRIDGE_SRC_ADDRESS" ]; then'; \
        echo '    export ICONBRIDGE_SRC_ADDRESS=$(cat ${ICONBRIDGE_SRC_ADDRESS})' ; \
        echo '  fi'; \
        echo '  if [ "$ICONBRIDGE_SRC_ENDPOINT" != "" ] && [ -f "$ICONBRIDGE_SRC_ENDPOINT" ]; then'; \
        echo '    export ICONBRIDGE_SRC_ENDPOINT=$(cat ${ICONBRIDGE_SRC_ENDPOINT})' ; \
        echo '  fi'; \
        echo '  if [ "$ICONBRIDGE_DST_ADDRESS" != "" ] && [ -f "$ICONBRIDGE_DST_ADDRESS" ]; then'; \
        echo '    export ICONBRIDGE_DST_ADDRESS=$(cat ${ICONBRIDGE_DST_ADDRESS})' ; \
        echo '  fi'; \
        echo '  if [ "$ICONBRIDGE_DST_ENDPOINT" != "" ] && [ -f "$ICONBRIDGE_DST_ENDPOINT" ]; then'; \
        echo '    export ICONBRIDGE_DST_ENDPOINT=$(cat ${ICONBRIDGE_DST_ENDPOINT})' ; \
        echo '  fi'; \
        echo '  if [ "$ICONBRIDGE_OFFSET" != "" ] && [ -f "$ICONBRIDGE_OFFSET" ]; then'; \
        echo '    export ICONBRIDGE_OFFSET=$(cat ${ICONBRIDGE_OFFSET})' ; \
        echo '  fi'; \
        echo '  sh -c "unset $UNSET ; $CMD"' ; \
        echo 'fi'; \
        echo 'exec "$@"'; \
    } > /entrypoint \
    && chmod +x /entrypoint
    
RUN chmod +x /iconbridge/run
ENTRYPOINT ["/iconbridge/run"]
