[package]
name = "bts"
version = "0.1.0"
authors = ["Icon Foundation<foo@icon.foundation>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
testable = []

[dependencies]
btp-common = { path = "../../../btp-common" }
libraries = { path = "../../libraries" }
near-sdk = "4.1.0-pre.3"
near-contract-standards = "4.1.0-pre.3"
tiny-keccak = { version = "2.0", features = ["fips202"] }

[dev-dependencies]
lazy_static = "1.4.0"

[[test]]
name = "test_ownership_management"
path = "tests/test_ownership_management.rs"

[[test]]
name = "test_token_transfer"
path = "tests/test_token_transfer.rs"

[[test]]
name = "test_token_management"
path = "tests/test_token_management.rs"

[[test]]
name = "test_handle_transfer_request"
path = "tests/test_handle_transfer_request.rs"

[[test]]
name = "test_fee_management"
path = "tests/test_fee_management.rs"

[[test]]
name = "test_coin_management"
path = "tests/test_coin_management.rs"

[[test]]
name = "test_coin_transfer"
path = "tests/test_coin_transfer.rs"

[[test]]
name = "test_blacklist_management"
path = "tests/test_blacklist_management.rs"