name: Deploy Node
on:
  push:
    paths:
      - 'provision/'
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        working-directory: ./provision
        run: |
             ls -al
