name: E2ETest

on:
  push:
    branches: [ e2eTestCI ]
    # paths:
    #   - 'cmd'
  pull_request:
    branches: [ e2eTestCI ]
    # paths:
    #   - 'cmd'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Checkout bls repo
      uses: actions/checkout@v3
      with:
        repository: harmony-one/bls.git
        path: bls
        ref: master

    - name: Checkout mcl repo
      uses: actions/checkout@v3
      with:
        repository: harmony-one/mcl.git
        path: mcl
        ref: master

    - name: Make bls
      run: |
           sudo apt install -y g++ gcc libssl-dev libgmp-dev
           cd bls
           sudo make -j8 BLS_SWAP_G=1
           sudo make install
           sudo make BLS_ETH=1 /usr/local/lib/libbls384_256.so
          #  sudo strip /home/runner/work/nethermind/nethermind/bls/lib/libbls384_256.so

    - name: Make mcl
      run: |
           cd mcl
           sudo make install

    - name: Test
      working-directory: ./cmd/e2etest
      run: |
           sudo apt-get install libc6-dev libgmp3-dev -y
           go run main.go
