name: E2ETest

on:
  push:
    branches: [ e2eTestCI ]
    # paths:
    #   - 'cmd'
  pull_request:
    branches: [ e2eTestCI ]
    # paths:
    #   - 'cmd'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Checkout bls repo
      uses: actions/checkout@v3
      with:
        repository: harmony-one/bls.git
        path: bls
        ref: master

    - name: Make bls
      run: |
           apt install -y g++ gcc
           cd bls
           make -j8 BLS_SWAP_G=1
           make install

    - name: Test
      working-directory: ./cmd/e2etest
      run: go run main.go
