name: E2ETest

on:
  push:
    branches: [ e2eTestCI ]
    paths:
      - 'cmd'
  pull_request:
    branches: [ e2eTestCI ]
    paths:
      - 'cmd'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      working-directory: ./cmd/e2etest
      run: go run main.go

