name: 'Register BTS in BMC'

on:
  workflow_dispatch:
  push:
    branches:
      - register-BTS-BMC-#343
  workflow_call:
jobs:
  register-bts-bmc:
    name: Register BTS contract as a service to BMC in testnet
    runs-on: ubuntu-latest
    container:
      image: iconbridge/build
      options: --user 1001
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Retrieve the secret and decode it to a file
        working-directory: ./javascore
        env:
          GOLOOP_RPC_KEY_STORE_B64: ${{ secrets.GOLOOP_RPC_KEY_STORE_B64 }}
        run: |
          echo $GOLOOP_RPC_KEY_STORE_B64 | base64 -d > key.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync tx files
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        run: |
          aws s3 cp s3://$AWS_S3_BUCKET/tx-icon-bmc ./javascore/tx-icon-bmc
          cat ./javascore/tx-icon-bmc | jq -r .scoreAddress > ./javascore/icon-addr-bmc
          aws s3 cp s3://$AWS_S3_BUCKET/tx-icon-bts ./javascore/tx-icon-bts
          cat ./javascore/tx-icon-bts | jq -r .scoreAddress > ./javascore/icon-addr-bts

      - name: Register BTS with BMC
        working-directory: ./javascore
        shell: bash
        timeout-minutes: 1
        env:
          GOLOOP_RPC_KEY_PASSWORD: ${{ secrets.GOLOOP_RPC_KEY_PASSWORD }}
          GOLOOP_RPC_URI: ${{ secrets.GOLOOP_RPC_URI }}
        run: |
          goloop rpc sendtx call --to $(cat icon-addr-bmc) \
                --method addService \
                --value 0 \
                --param _addr=$(cat icon-addr-bts) \
                --param _svc="bts" \
                --step_limit=3000000000 \
                --uri $GOLOOP_RPC_URI \
                --key_store=./key.json \
                --nid=0x2 | tee | jq -r . > tx.icon.bts.bmc

      - name: Deployment txresult
        working-directory: ./javascore
        shell: bash
        timeout-minutes: 1
        env:
          GOLOOP_RPC_URI: ${{ secrets.GOLOOP_RPC_URI }}
        run: |
          while true; do
            str=`goloop rpc --uri $GOLOOP_RPC_URI txresult $(cat tx.icon.bts.bmc) | tee tx-icon-bts-bmc || exit 0`
            echo Output: $str
            if [[ $str =~ logsBloom ]]; then
              break
            fi
            echo Wait
            sleep 2
          done
          echo Finished

      - name: Sync tx-icon-bts-bmc
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        run: |
          aws s3 cp ./javascore/tx-icon-bts-bmc s3://$AWS_S3_BUCKET/tx-icon-bts-bmc-$GITHUB_REF_NAME
          aws s3 mv ./javascore/tx-icon-bts-bmc s3://$AWS_S3_BUCKET/tx-icon-bts-bmc
